#!/usr/bin/env bash

set -e

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 VERSION" >&2
	exit 1
fi

VERSION=${1}
: ${ARCH:="$(go env GOARCH)"}

case ${ARCH} in
amd64)
	DOCKERFILE="Dockerfile-release"
	;;
ppc64le)
	DOCKERFILE="Dockerfile-release.cross"
	DOCKER_ARGS="--build-arg DOCKER_FROM=\"ppc64le/alpine:latest\""
	VERSION+="-${ARCH}"
	;;
arm64)
	DOCKERFILE="Dockerfile-release.cross"
	DOCKER_ARGS="--build-arg DOCKER_FROM=\"arm64v8/alpine:latest\""
	VERSION+="-${ARCH}"
	;;
*)
	echo "ERROR: Unknown arch ${ARCH}."
	exit 1
	;;
esac

if [ -z "${BINARYDIR}" ]; then
	RELEASE="etcd-${1}"-$(go env GOOS)-$(go env GOARCH)
	BINARYDIR="${RELEASE}"
	TARFILE="${RELEASE}.tar.gz"
	TARURL="https://github.com/coreos/etcd/releases/download/${1}/${TARFILE}"
	if ! curl -f -L -o "${TARFILE}" "${TARURL}" ; then
		echo "Failed to download ${TARURL}."
		exit 1
	fi
	tar -zvxf "${TARFILE}"
fi

BINARYDIR=${BINARYDIR:-.}
BUILDDIR=${BUILDDIR:-.}

IMAGEDIR=${BUILDDIR}/image-docker

mkdir -p "${IMAGEDIR}"/var/etcd
mkdir -p "${IMAGEDIR}"/var/lib/etcd
cp "${BINARYDIR}"/etcd "${BINARYDIR}"/etcdctl "${IMAGEDIR}"

cat ./"${DOCKERFILE}" > "${IMAGEDIR}"/Dockerfile

if [ -z "$TAG" ]; then
    docker build -t "gcr.io/etcd-development/etcd:${VERSION}" ${DOCKER_ARGS} "${IMAGEDIR}"
    docker build -t "quay.io/coreos/etcd:${VERSION}" ${DOCKER_ARGS} "${IMAGEDIR}"
else
    docker build -t "${TAG}:${VERSION}" ${DOCKER_ARGS} "${IMAGEDIR}"
fi
